name: Web Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2

      - name: Install Dependencies
        run: bun install

      - name: Pull environment variables
        working-directory: packages/next
        run: bun vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project
        working-directory: packages/next
        run: bun vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy to Vercel
        working-directory: packages/next
        run: bun vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
